import type { Listing } from "./listings";

export type Kreis = "Westen" | "Centrum" | "Osten";

export type Quartier = {
  slug: string;
  name: string;
  kreis: Kreis;
  group: string;
  lat: number;
  lng: number;
  description: string;
  rent: string;
  safety: number;
  transport: number;
  nightlife: number;
  studentFit: number;
  commute: string;
  bestFor: string;
  caution: string;
  landmarks: string[];
};

export const kreisLabels: Record<Kreis, string> = {
  Westen: "Westen",
  Centrum: "Centrum",
  Osten: "Osten",
};

export const stGallenQuartiere: Quartier[] = [
  {
    slug: "altstadt",
    name: "Altstadt",
    kreis: "Centrum",
    group: "Innenstadt",
    lat: 47.424895390418534,
    lng: 9.376442650046648,
    description:
      "St.Gallen's UNESCO-listed old town, built around the Abbey and its famous library. Cobbled lanes, oriel windows, and the city's main shopping street run through it — beautiful and central, but among the pricier and busier places to live.",
    rent: "CHF 850–1,200/mo",
    safety: 9.0,
    transport: 9.2,
    nightlife: 7.5,
    studentFit: 8.0,
    commute: "10–15 min to HSG by foot or bus",
    bestFor: "UNESCO old town living, cafés and bars, very walkable",
    caution: "Higher rents and tourist foot traffic around the Abbey square",
    landmarks: ["Abbey District (Stiftsbezirk)", "Marktplatz", "Multergasse", "Bohl"],
  },
  {
    slug: "st-leonhard-ost",
    name: "St.Leonhard-Ost",
    kreis: "Centrum",
    group: "Innenstadt",
    lat: 47.421910295275474,
    lng: 9.370688000614628,
    description:
      "A mixed residential and commercial quarter right next to the main train station, popular for its unbeatable connectivity to the rest of Switzerland.",
    rent: "CHF 800–1,150/mo",
    safety: 8.6,
    transport: 9.3,
    nightlife: 6.5,
    studentFit: 7.8,
    commute: "10 min to HSG by bus",
    bestFor: "Right next to the main train station, easy weekend trips",
    caution: "Traffic and some noise near the station and Poststrasse",
    landmarks: ["Bahnhof St.Gallen", "Poststrasse", "Vadianstrasse"],
  },
  {
    slug: "hoelzli-joosrueti",
    name: "Hölzli-Joosrüti",
    kreis: "Centrum",
    group: "Rosenberg",
    lat: 47.43572896493153,
    lng: 9.365564733693233,
    description:
      "A quiet hillside residential quarter directly below the HSG campus, favored by students who want the shortest possible walk to lectures without living right on campus.",
    rent: "CHF 800–1,100/mo",
    safety: 9.0,
    transport: 8.0,
    nightlife: 5.0,
    studentFit: 9.3,
    commute: "5–10 min walk to HSG",
    bestFor: "Closest residential quarter to campus, quiet hillside streets",
    caution: "Steep streets and limited nightlife of its own",
    landmarks: ["HSG main campus", "Kreuzbleiche sports ground", "Rosenbergstrasse"],
  },
  {
    slug: "rosenberg-kreubleiche",
    name: "Rosenberg-Kreubleiche",
    kreis: "Centrum",
    group: "Rosenberg",
    lat: 47.42236314286388,
    lng: 9.364281209852505,
    description:
      "Home to the University of St.Gallen itself — the shortest possible commute to lectures, wrapped in forest trails and the Kreuzbleiche sports complex. The single most in-demand quarter for HSG students.",
    rent: "CHF 800–1,150/mo",
    safety: 9.1,
    transport: 8.2,
    nightlife: 5.2,
    studentFit: 9.5,
    commute: "0–5 min walk to HSG",
    bestFor: "HSG's own neighborhood — walk to every lecture",
    caution: "Extremely popular with students, so rooms are scarce and go fast",
    landmarks: ["University of St.Gallen (HSG)", "Kreuzbleicheweiher pond", "Rosenberg forest trails"],
  },
  {
    slug: "riethuesli",
    name: "Riethüsli",
    kreis: "Centrum",
    group: "Riethüsli",
    lat: 47.41049970918256,
    lng: 9.365121403431786,
    description:
      "A green, family-oriented residential quarter north of the center, anchored by the city's main athletics center and surrounding forest.",
    rent: "CHF 700–1,000/mo",
    safety: 8.8,
    transport: 7.6,
    nightlife: 4.0,
    studentFit: 7.0,
    commute: "15–20 min to HSG by bus",
    bestFor: "Quiet, green residential living popular with families",
    caution: "Fewer amenities nearby and an uphill commute to campus",
    landmarks: ["Athletik Zentrum St.Gallen", "Riethüsli forest"],
  },
  {
    slug: "st-georgen-bernegg",
    name: "St.Georgen-Bernegg",
    kreis: "Centrum",
    group: "St.Georgen",
    lat: 47.4148866837884,
    lng: 9.377268778893695,
    description:
      "A calm residential quarter south of the center, close to the Cantonal Hospital, with a mix of older apartment blocks and single-family homes.",
    rent: "CHF 750–1,050/mo",
    safety: 8.5,
    transport: 8.0,
    nightlife: 5.0,
    studentFit: 7.2,
    commute: "15 min to HSG by bus",
    bestFor: "Close to the Cantonal Hospital, calm residential streets",
    caution: "A longer commute to campus and mostly residential character",
    landmarks: ["Kantonsspital St.Gallen", "Sonnenstrasse"],
  },
  {
    slug: "st-georgen-bach",
    name: "St.Georgen-Bach",
    kreis: "Centrum",
    group: "St.Georgen",
    lat: 47.41694212078138,
    lng: 9.394454615665977,
    description:
      "A greener, hillside continuation of St.Georgen further from the center, popular with people who want more space and don't mind a longer commute.",
    rent: "CHF 700–950/mo",
    safety: 8.3,
    transport: 7.0,
    nightlife: 3.5,
    studentFit: 6.0,
    commute: "20–25 min to HSG",
    bestFor: "Green, hillside living away from the center",
    caution: "Lower bus frequency and more distance from campus",
    landmarks: ["Bachtobel nature area"],
  },
  {
    slug: "stuelegg-rueti",
    name: "Stuelegg-Rüti",
    kreis: "Centrum",
    group: "St.Georgen",
    lat: 47.40813615676788,
    lng: 9.400493482482673,
    description:
      "The southernmost, most rural edge of the Centrum district — affordable but a real commute from both campus and the city center.",
    rent: "CHF 650–900/mo",
    safety: 8.2,
    transport: 6.5,
    nightlife: 3.0,
    studentFit: 5.2,
    commute: "25–30 min to HSG",
    bestFor: "Rural and affordable for students who don't mind a longer commute",
    caution: "Sparse public transport and far from campus and nightlife",
    landmarks: ["Rüti forest trails"],
  },
  {
    slug: "st-jakob",
    name: "St.Jakob",
    kreis: "Centrum",
    group: "St.Jakob",
    lat: 47.430851474978425,
    lng: 9.379776120501234,
    description:
      "A central, well-connected quarter east of the old town, home to the Kantonsschule and a lively stretch of shops along Rorschacher Strasse.",
    rent: "CHF 780–1,080/mo",
    safety: 8.7,
    transport: 8.5,
    nightlife: 6.0,
    studentFit: 7.9,
    commute: "10–15 min to HSG",
    bestFor: "Central and well-connected, close to shops on Rorschacher Strasse",
    caution: "Busier main roads run directly through the quarter",
    landmarks: ["Kantonsschule am Burggraben", "Rorschacher Strasse"],
  },
  {
    slug: "linsenbuehl-dreilinden",
    name: "Linsenbühl-Dreilinden",
    kreis: "Centrum",
    group: "Linsenbühl-Dreilinden",
    lat: 47.423973399238186,
    lng: 9.385272365585038,
    description:
      "An established residential quarter just east of the center, mostly older apartment buildings on quiet, tree-lined streets.",
    rent: "CHF 750–1,050/mo",
    safety: 8.6,
    transport: 8.3,
    nightlife: 5.5,
    studentFit: 7.5,
    commute: "12–18 min to HSG",
    bestFor: "Established residential streets close to the center",
    caution: "Mostly long-term family flats, fewer student-specific listings",
    landmarks: ["Dreilindenpark", "Linsebühlkirche"],
  },
  {
    slug: "rotmonten",
    name: "Rotmonten",
    kreis: "Osten",
    group: "Rotmonten",
    lat: 47.44343440330589,
    lng: 9.378198036002273,
    description:
      "An upscale hillside quarter on the city's northeastern edge, known for panoramic views over St.Gallen and a golf course — quiet, green, and car-oriented.",
    rent: "CHF 850–1,200/mo",
    safety: 9.2,
    transport: 6.8,
    nightlife: 2.5,
    studentFit: 5.0,
    commute: "20–25 min to HSG",
    bestFor: "Upscale hillside living with panoramic views over the city",
    caution: "Higher rents for a mostly residential, car-oriented area",
    landmarks: ["Rotmonten viewpoint", "Golf Club Waldkirch (nearby)"],
  },
  {
    slug: "langgass-heiligkreuz",
    name: "Langgass-Heiligkreuz",
    kreis: "Osten",
    group: "Langgass-Heiligkreuz",
    lat: 47.440579031692394,
    lng: 9.39248516250213,
    description:
      "A calm residential quarter in the city's northeast, mostly family housing with good bus connections back into the center.",
    rent: "CHF 700–1,000/mo",
    safety: 8.5,
    transport: 8.0,
    nightlife: 4.5,
    studentFit: 6.8,
    commute: "15–20 min to HSG",
    bestFor: "Calm residential streets with good bus connections",
    caution: "Mostly family housing with limited student-specific inventory",
    landmarks: ["Heiligkreuz church", "Langgass school"],
  },
  {
    slug: "st-fiden-krontal",
    name: "St.Fiden-Krontal",
    kreis: "Osten",
    group: "St.Fiden",
    lat: 47.43180545423914,
    lng: 9.397102013250862,
    description:
      "A residential quarter built around its own S-Bahn station, useful for regional day trips but a bit removed from the university and nightlife core.",
    rent: "CHF 700–980/mo",
    safety: 8.3,
    transport: 8.6,
    nightlife: 4.0,
    studentFit: 6.5,
    commute: "18–22 min to HSG (train + short walk)",
    bestFor: "Own S-Bahn station (St.Fiden), handy for regional day trips",
    caution: "Somewhat removed from the university and nightlife core",
    landmarks: ["St.Fiden train station", "Kantonsspital St.Gallen (east wing)"],
  },
  {
    slug: "notkersegg",
    name: "Notkersegg",
    kreis: "Osten",
    group: "Notkersegg",
    lat: 47.423622371475,
    lng: 9.401509314174412,
    description:
      "A forested hillside quarter on the eastern edge of the city, best known for the Peter and Paul wildlife park right at its doorstep.",
    rent: "CHF 650–900/mo",
    safety: 8.8,
    transport: 5.5,
    nightlife: 1.5,
    studentFit: 4.0,
    commute: "25–30 min to HSG",
    bestFor: "Forest and nature immediately at your doorstep",
    caution: "Sparse bus service and a long commute to campus",
    landmarks: ["Wildpark Peter and Paul"],
  },
  {
    slug: "kurzegg-rank",
    name: "Kurzegg-Rank",
    kreis: "Osten",
    group: "Notkersegg",
    lat: 47.418118002925155,
    lng: 9.421823906913803,
    description:
      "A quiet, rural quarter on the far eastern edge of the city, best suited to students with a car or a strong tolerance for infrequent buses.",
    rent: "CHF 620–870/mo",
    safety: 8.7,
    transport: 5.0,
    nightlife: 1.2,
    studentFit: 3.5,
    commute: "28–33 min to HSG",
    bestFor: "Quiet rural living for those with a car",
    caution: "Very limited public transport and far from everything",
    landmarks: ["Rank forest"],
  },
  {
    slug: "hub-schaugentobel",
    name: "Hub-Schaugentobel",
    kreis: "Osten",
    group: "Notkersegg",
    lat: 47.4308380498057,
    lng: 9.421919381395126,
    description:
      "A rural hillside quarter near the dramatic Schaugentobel gorge, popular with hikers but far from campus and city life.",
    rent: "CHF 620–870/mo",
    safety: 8.7,
    transport: 5.2,
    nightlife: 1.2,
    studentFit: 3.6,
    commute: "25–30 min to HSG",
    bestFor: "Rural hillside living close to hiking trails",
    caution: "Sparse transport links and a long commute to campus",
    landmarks: ["Schaugentobel gorge"],
  },
  {
    slug: "achslen-wilen",
    name: "Achslen-Wilen",
    kreis: "Osten",
    group: "Neudorf",
    lat: 47.44127794131749,
    lng: 9.419527683051056,
    description:
      "A low-density, green quarter on the far eastern edge of the city, mostly single-family homes with generous gardens.",
    rent: "CHF 700–950/mo",
    safety: 8.4,
    transport: 6.0,
    nightlife: 2.0,
    studentFit: 4.2,
    commute: "25–30 min to HSG",
    bestFor: "Green, low-density living on the edge of the city",
    caution: "Long commute and thin evening public transport",
    landmarks: ["Wilen reservoir"],
  },
  {
    slug: "stephanshorn-zil-kesselhalden",
    name: "Stephanshorn-Zil-Kesselhalden",
    kreis: "Osten",
    group: "Neudorf",
    lat: 47.445505830750356,
    lng: 9.40794672981609,
    description:
      "The city's far eastern edge near the Stephanshorn business park and the Lake Constance shoreline — pleasant, but a genuine commute to the university.",
    rent: "CHF 750–1,050/mo",
    safety: 8.5,
    transport: 6.8,
    nightlife: 2.5,
    studentFit: 4.5,
    commute: "25–30 min to HSG",
    bestFor: "Close to the Stephanshorn business park and the lake shore",
    caution: "Far from the university and the old town",
    landmarks: ["Stephanshorn business park", "Lake Constance shoreline"],
  },
  {
    slug: "vonwil-lachen-schoren",
    name: "Vonwil-Lachen-Schoren",
    kreis: "Westen",
    group: "Lachen",
    lat: 47.42385489591837,
    lng: 9.352880576776721,
    description:
      "A well-connected quarter just west of the main station, closer to the center than most of the Westen district and popular with commuters.",
    rent: "CHF 750–1,050/mo",
    safety: 8.4,
    transport: 8.8,
    nightlife: 5.5,
    studentFit: 7.0,
    commute: "12–15 min to HSG (bus via the center)",
    bestFor: "Well connected, close to the main station's western side",
    caution: "Busier streets near the station and rail lines",
    landmarks: ["St.Gallen main station (west side)", "Vonwil bridge"],
  },
  {
    slug: "sittertobel",
    name: "Sittertobel",
    kreis: "Westen",
    group: "Bruggen",
    lat: 47.41743074593706,
    lng: 9.330739680232274,
    description:
      "A quarter defined by the dramatic Sitter gorge and its viaduct, popular for walks but light on housing and amenities of its own.",
    rent: "CHF 650–900/mo",
    safety: 8.6,
    transport: 6.0,
    nightlife: 1.5,
    studentFit: 4.5,
    commute: "20–25 min to HSG",
    bestFor: "Right by the dramatic Sitter gorge, popular for walks",
    caution: "Limited transport frequency and few amenities nearby",
    landmarks: ["Sitter gorge (Sittertobel)", "Kubel Viaduct"],
  },
  {
    slug: "bruggen-zuercherstrasse",
    name: "Bruggen-Zürcherstrasse",
    kreis: "Westen",
    group: "Bruggen",
    lat: 47.41020301750962,
    lng: 9.329127833707489,
    description:
      "The western district's own local center, with its own train station and a stretch of everyday shops along Zürcher Strasse.",
    rent: "CHF 680–950/mo",
    safety: 8.0,
    transport: 8.0,
    nightlife: 4.5,
    studentFit: 6.0,
    commute: "18–22 min to HSG (train via the main station)",
    bestFor: "Own train station (Bruggen) and local shops on Zürcher Strasse",
    caution: "A transfer at the main station is usually needed to reach HSG",
    landmarks: ["Bruggen train station", "Zürcher Strasse shops"],
  },
  {
    slug: "boppartshof-hinterberg",
    name: "Boppartshof-Hinterberg",
    kreis: "Westen",
    group: "Bruggen",
    lat: 47.40347224124379,
    lng: 9.332095034762094,
    description:
      "An affordable residential quarter west of the center, mostly mid-century apartment blocks around a green park.",
    rent: "CHF 650–900/mo",
    safety: 8.2,
    transport: 6.5,
    nightlife: 2.0,
    studentFit: 4.8,
    commute: "22–25 min to HSG",
    bestFor: "Affordable residential streets west of the center",
    caution: "Longer commute and fewer amenities nearby",
    landmarks: ["Hinterberg residential park"],
  },
  {
    slug: "haggen-oberstrasse-langweid",
    name: "Haggen-Oberstrasse-Langweid",
    kreis: "Westen",
    group: "Bruggen",
    lat: 47.407775924788105,
    lng: 9.34800586968734,
    description:
      "A quiet, mostly family-oriented residential quarter southwest of the center, built around local sports fields.",
    rent: "CHF 650–900/mo",
    safety: 8.1,
    transport: 6.8,
    nightlife: 2.0,
    studentFit: 4.9,
    commute: "20–24 min to HSG",
    bestFor: "Quiet, affordable, mostly family housing",
    caution: "Limited nightlife and few student-specific listings",
    landmarks: ["Haggen sports fields"],
  },
  {
    slug: "moos-waldacker-lerchenfeld",
    name: "Moos-Waldacker-Lerchenfeld",
    kreis: "Westen",
    group: "Bruggen",
    lat: 47.414973274892844,
    lng: 9.342852887971146,
    description:
      "A green, low-density residential quarter west of the center, popular with families for its parks and quiet streets.",
    rent: "CHF 650–900/mo",
    safety: 8.2,
    transport: 6.5,
    nightlife: 1.8,
    studentFit: 4.5,
    commute: "20–25 min to HSG",
    bestFor: "Green, low-density residential streets",
    caution: "Sparse evening bus service",
    landmarks: ["Lerchenfeld park"],
  },
  {
    slug: "hafnersberg",
    name: "Hafnersberg",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.41663379025604,
    lng: 9.30184516530011,
    description:
      "The far western edge of the city, next to light industry, with the lowest rents St.Gallen has to offer.",
    rent: "CHF 600–850/mo",
    safety: 7.8,
    transport: 5.8,
    nightlife: 1.5,
    studentFit: 3.5,
    commute: "25–30 min to HSG",
    bestFor: "Cheapest rents in the city, quiet edge-of-town feel",
    caution: "Industrial surroundings and a long commute to campus",
    landmarks: ["Hafnersberg industrial area"],
  },
  {
    slug: "breitfeld-gruendenmoos",
    name: "Breitfeld-Gründenmoos",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.409992926370116,
    lng: 9.303446941949225,
    description:
      "An affordable far-western quarter next to the Gründenmoos nature reserve, popular with commuters who work rather than study in the city.",
    rent: "CHF 600–850/mo",
    safety: 7.9,
    transport: 6.0,
    nightlife: 1.5,
    studentFit: 3.6,
    commute: "24–28 min to HSG",
    bestFor: "Affordable, close to the Gründenmoos nature reserve",
    caution: "Far from the university and city nightlife",
    landmarks: ["Gründenmoos nature reserve"],
  },
  {
    slug: "winkeln-nord-industrie",
    name: "Winkeln Nord-Industrie",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.405660378242224,
    lng: 9.299615158246024,
    description:
      "A working industrial quarter around its own train station, with a growing number of converted warehouse-style flats at low rents.",
    rent: "CHF 600–850/mo",
    safety: 7.5,
    transport: 7.5,
    nightlife: 1.0,
    studentFit: 3.8,
    commute: "20–25 min to HSG (train via the main station)",
    bestFor: "Own train station (Winkeln) and cheap warehouse-style flats",
    caution: "Industrial surroundings with little residential character",
    landmarks: ["Winkeln train station", "Industrie Winkeln"],
  },
  {
    slug: "winkeln-sued",
    name: "Winkeln Süd",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.39984712207282,
    lng: 9.299592896714982,
    description:
      "A quiet residential pocket on the southwestern edge of the city, close to the Gübsensee lake.",
    rent: "CHF 600–850/mo",
    safety: 7.7,
    transport: 6.5,
    nightlife: 1.2,
    studentFit: 3.5,
    commute: "22–27 min to HSG",
    bestFor: "Quiet southwestern edge of the city",
    caution: "Sparse transport in the evenings",
    landmarks: ["Gübsensee lake (nearby)"],
  },
  {
    slug: "guebsensee",
    name: "Gübsensee",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.40018688443861,
    lng: 9.313572737090757,
    description:
      "Built around the popular Gübsensee lake, a favorite spot for swimming and jogging in the warmer months.",
    rent: "CHF 620–870/mo",
    safety: 8.0,
    transport: 6.2,
    nightlife: 1.3,
    studentFit: 3.8,
    commute: "22–26 min to HSG",
    bestFor: "Right by the Gübsensee lake, popular for swimming and jogging",
    caution: "Limited transport and distance from campus",
    landmarks: ["Gübsensee lake"],
  },
  {
    slug: "chraezeren",
    name: "Chräzeren",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.405118100467725,
    lng: 9.31375951405936,
    description:
      "A quiet residential pocket in the western Winkeln area, mostly low-rise housing surrounded by farmland and woods.",
    rent: "CHF 610–860/mo",
    safety: 7.9,
    transport: 6.0,
    nightlife: 1.2,
    studentFit: 3.6,
    commute: "23–27 min to HSG",
    bestFor: "Quiet, affordable residential streets",
    caution: "Far from campus and the city center",
    landmarks: ["Chräzeren woods"],
  },
  {
    slug: "altenwegen",
    name: "Altenwegen",
    kreis: "Westen",
    group: "Winkeln",
    lat: 47.41169906068609,
    lng: 9.315297312563432,
    description:
      "A small residential pocket near Gübsensee, affordable and quiet but a genuine trip from campus and the city center.",
    rent: "CHF 610–860/mo",
    safety: 7.8,
    transport: 6.1,
    nightlife: 1.2,
    studentFit: 3.7,
    commute: "22–26 min to HSG",
    bestFor: "Affordable and quiet, close to Gübsensee",
    caution: "Long commute and limited evening transport",
    landmarks: ["Altenwegen farmland"],
  },
];

export type QuartierListing = Listing & { quartierSlug: string };

export const stGallenListings: QuartierListing[] = [
  {
    id: "ha-rosenberg-room",
    quartierSlug: "rosenberg-kreubleiche",
    title: "Sunny room 5 minutes from HSG",
    rent: 850,
    currency: "CHF ",
    type: "Room",
    source: "HousingAtlas",
    featured: true,
    homeUniversityFriendly: true,
    lat: 47.4229,
    lng: 9.3635,
    description:
      "A bright, furnished room in a shared flat on Rosenbergstrasse, a five-minute walk from the HSG main building. The landlord has hosted exchange students for years and knows exactly what incoming students need.",
    rooms: 1,
    sizeSqm: 15,
    availableFrom: "1 Sep 2026",
    amenities: ["Furnished", "Wifi included", "Washing machine", "Bills included"],
  },
  {
    id: "ha-kreuzbleiche-studio",
    quartierSlug: "hoelzli-joosrueti",
    title: "Compact studio near Kreuzbleiche",
    rent: 1050,
    currency: "CHF ",
    type: "Studio",
    source: "HousingAtlas",
    homeUniversityFriendly: true,
    lat: 47.4351,
    lng: 9.3648,
    description:
      "A self-contained studio in Hölzli-Joosrüti, a short walk from the Kreuzbleiche sports ground and the HSG campus, ideal for a student who wants their own space without a long commute.",
    rooms: 1,
    sizeSqm: 26,
    availableFrom: "15 Sep 2026",
    amenities: ["Furnished", "Private bathroom", "Kitchenette", "Wifi included"],
  },
  {
    id: "wg-zimmer-altstadt-room",
    quartierSlug: "altstadt",
    title: "Historic room in the Old Town",
    rent: 900,
    currency: "CHF ",
    type: "Room",
    source: "WG-Zimmer.ch",
    lat: 47.4246,
    lng: 9.3771,
    description:
      "A room in a shared flat above a café on a cobbled Altstadt lane, two minutes from the Abbey District — full old-town charm, with the tradeoff of some weekend foot traffic below.",
    rooms: 1,
    sizeSqm: 12,
    availableFrom: "1 Oct 2026",
    amenities: ["Furnished", "Wifi included", "Shared kitchen"],
    sourceUrl: "https://www.wgzimmer.ch",
  },
  {
    id: "flatfox-st-leonhard-studio",
    quartierSlug: "st-leonhard-ost",
    title: "Studio steps from the train station",
    rent: 1080,
    currency: "CHF ",
    type: "Studio",
    source: "Flatfox",
    lat: 47.4224,
    lng: 9.3695,
    description:
      "A self-contained studio in St.Leonhard-Ost, a two-minute walk from the main train station — ideal for students who travel often or want the fastest possible connection to the rest of Switzerland.",
    rooms: 1,
    sizeSqm: 24,
    availableFrom: "1 Sep 2026",
    amenities: ["Furnished", "Private bathroom", "Kitchenette"],
    sourceUrl: "https://flatfox.ch",
  },
  {
    id: "homegate-linsenbuehl-room",
    quartierSlug: "linsenbuehl-dreilinden",
    title: "Quiet room in a family flat",
    rent: 850,
    currency: "CHF ",
    type: "Room",
    source: "Homegate",
    riskNote: "Higher caution",
    lat: 47.4236,
    lng: 9.3861,
    description:
      "A room sublet within a long-term family flat on a quiet residential street — listed with limited photos and no verified reviews yet, worth extra diligence before committing given the caution flag.",
    rooms: 1,
    sizeSqm: 16,
    availableFrom: "15 Sep 2026",
    amenities: ["Furnished", "Wifi included"],
    sourceUrl: "https://www.homegate.ch",
  },
];

export function getQuartierBySlug(slug: string): Quartier | undefined {
  return stGallenQuartiere.find((q) => q.slug === slug);
}

export function getListingsForQuartierSlug(slug: string | null): Listing[] {
  if (!slug) return [];
  return stGallenListings.filter((l) => l.quartierSlug === slug);
}
